/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                name: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                            meta: {
                                total: number;
                                page: number;
                                limit: number;
                                totalPages: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: email */
                            email: string;
                            name: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: unknown[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: email */
                            email: string;
                            name: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: unknown[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: unknown[];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update user */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: email */
                            email: string;
                            name: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            statusCode: number;
                            error: string;
                            message: string;
                            details?: unknown[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receitas do mês */
        get: {
            parameters: {
                query?: {
                    month?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary: {
                                totalReceived: {
                                    amount: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "currency";
                                        direction: "up" | "down" | "neutral";
                                        comparisonLabel?: string;
                                    };
                                };
                                toReceive: {
                                    amount: number;
                                    pendingCount: number;
                                };
                                topSource: string;
                            };
                            entries: {
                                /** Format: uuid */
                                id: string;
                                /** Format: date */
                                date: string;
                                description: string;
                                category: string;
                                status: "received" | "pending";
                                amount: number;
                            }[];
                            history: {
                                label: string;
                                value: number;
                            }[];
                            sources: {
                                id: string;
                                name: string;
                                amount: number;
                                percent: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/income/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar lançamento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date: string;
                        description: string;
                        category: string;
                        status?: "received" | "pending";
                        amount?: number;
                        daysWorked?: number;
                        hoursPerDay?: number;
                        hourlyRate?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            date: string;
                            description: string;
                            category: string;
                            status: "received" | "pending";
                            amount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/income/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Excluir lançamento */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualizar lançamento */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date?: string;
                        description?: string;
                        category?: string;
                        status?: "received" | "pending";
                        amount?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            date: string;
                            description: string;
                            category: string;
                            status: "received" | "pending";
                            amount: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/expenses/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview de despesas */
        get: {
            parameters: {
                query?: {
                    month?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary: {
                                totalSpent: {
                                    amount: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "currency";
                                        direction: "up" | "down" | "neutral";
                                        comparisonLabel?: string;
                                    };
                                };
                                monthlyLimit: {
                                    limit: number;
                                    spent: number;
                                    remaining: number;
                                    usedPercent: number;
                                };
                            };
                            byCategory: {
                                total: number;
                                items: {
                                    category: string;
                                    amount: number;
                                    percent: number;
                                }[];
                            };
                            recent: {
                                /** Format: uuid */
                                id: string;
                                description: string;
                                category: string;
                                date: string;
                                amount: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todas as despesas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            date: string;
                            description: string;
                            category: string;
                            paymentMethod?: "credit" | "debit" | "pix" | "cash" | "boleto";
                            amount: number;
                            /** Format: date */
                            billingDate: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Criar lançamento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date: string;
                        description: string;
                        category: string;
                        paymentMethod?: "credit" | "debit" | "pix" | "cash" | "boleto";
                        amount: number;
                        recurringMonths?: number;
                        installments?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            date: string;
                            description: string;
                            category: string;
                            paymentMethod?: "credit" | "debit" | "pix" | "cash" | "boleto";
                            amount: number;
                            /** Format: date */
                            billingDate: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Excluir lançamento */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualizar lançamento */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date?: string;
                        description?: string;
                        category?: string;
                        paymentMethod?: "credit" | "debit" | "pix" | "cash" | "boleto";
                        amount?: number;
                        recurringMonths?: number;
                        installments?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: date */
                            date: string;
                            description: string;
                            category: string;
                            paymentMethod?: "credit" | "debit" | "pix" | "cash" | "boleto";
                            amount: number;
                            /** Format: date */
                            billingDate: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/expenses/limit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Limite mensal */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            limit: number;
                        };
                    };
                };
            };
        };
        /** Atualizar limite */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        limit: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            limit: number;
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter resumo de investimentos */
        get: {
            parameters: {
                query?: {
                    range?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary: {
                                investedNetWorth: {
                                    amount: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "currency";
                                        direction: "up" | "down" | "neutral";
                                        comparisonLabel?: string;
                                    };
                                };
                                monthlyYield: {
                                    amount: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "currency";
                                        direction: "up" | "down" | "neutral";
                                        comparisonLabel?: string;
                                    };
                                };
                                yearlyYield: {
                                    amount: number;
                                    returnPercentYtd: number;
                                };
                            };
                            allocation: {
                                total: number;
                                items: {
                                    assetClass: string;
                                    percent: number;
                                }[];
                            };
                            evolution: {
                                label: string;
                                value: number;
                            }[];
                            assets: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                assetClass: string;
                                subtitle?: string;
                                currentBalance: number;
                                weightPercent: number;
                                monthlyYield: {
                                    amount: number;
                                    percent: number;
                                };
                                totalInvested?: number;
                                averagePrice?: number;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investments/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar ativo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        assetClass: string;
                        subtitle?: string;
                        currentBalance: number;
                        totalInvested?: number;
                        averagePrice?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            assetClass: string;
                            subtitle?: string;
                            currentBalance: number;
                            weightPercent: number;
                            monthlyYield: {
                                amount: number;
                                percent: number;
                            };
                            totalInvested?: number;
                            averagePrice?: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/investments/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover ativo */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualizar ativo */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        assetClass?: string;
                        subtitle?: string;
                        currentBalance?: number;
                        totalInvested?: number;
                        averagePrice?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            assetClass: string;
                            subtitle?: string;
                            currentBalance: number;
                            weightPercent: number;
                            monthlyYield: {
                                amount: number;
                                percent: number;
                            };
                            totalInvested?: number;
                            averagePrice?: number;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar metas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary: {
                                activeCount: number;
                                completedCount: number;
                                totalSaved: number;
                            };
                            goals: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                description?: string;
                                priority: "high" | "medium" | "low";
                                status: "active" | "completed";
                                currentAmount: number;
                                targetAmount: number;
                                progressPercent: number;
                                remaining: number;
                                forecastDate: string;
                                icon: string;
                                color: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Criar meta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string;
                        priority: "high" | "medium" | "low";
                        targetAmount: number;
                        currentAmount: number;
                        icon: string;
                        color: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            description?: string;
                            priority: "high" | "medium" | "low";
                            status: "active" | "completed";
                            currentAmount: number;
                            targetAmount: number;
                            progressPercent: number;
                            remaining: number;
                            forecastDate: string;
                            icon: string;
                            color: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Excluir meta */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualizar meta */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string;
                        priority?: "high" | "medium" | "low";
                        targetAmount?: number;
                        currentAmount?: number;
                        icon?: string;
                        color?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            description?: string;
                            priority: "high" | "medium" | "low";
                            status: "active" | "completed";
                            currentAmount: number;
                            targetAmount: number;
                            progressPercent: number;
                            remaining: number;
                            forecastDate: string;
                            icon: string;
                            color: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/goals/{id}/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adicionar aporte à meta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        amount: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            description?: string;
                            priority: "high" | "medium" | "low";
                            status: "active" | "completed";
                            currentAmount: number;
                            targetAmount: number;
                            progressPercent: number;
                            remaining: number;
                            forecastDate: string;
                            icon: string;
                            color: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: {
                                id: string;
                                name: string;
                                email: string;
                                avatarUrl?: string;
                            };
                            token: string;
                            /** Format: date-time */
                            expiresAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            name: string;
                            email: string;
                            avatarUrl?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/net-worth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Patrimônio líquido */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            amount: number;
                            changePercent: number;
                            changeLabel: string;
                            sparkline: number[];
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visão geral */
        get: {
            parameters: {
                query?: {
                    month?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            metrics: {
                                totalIncome: {
                                    value: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "brl";
                                        direction: "up" | "down";
                                        comparisonLabel?: string;
                                    };
                                };
                                totalExpenses: {
                                    value: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "brl";
                                        direction: "up" | "down";
                                        comparisonLabel?: string;
                                    };
                                };
                                monthlyBalance: {
                                    value: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "brl";
                                        direction: "up" | "down";
                                        comparisonLabel?: string;
                                    };
                                };
                                savingsRate: {
                                    value: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "brl";
                                        direction: "up" | "down";
                                        comparisonLabel?: string;
                                    };
                                };
                            };
                            monthlyFlow: {
                                income: {
                                    id: string;
                                    label: string;
                                    color: string;
                                    points: {
                                        label: string;
                                        value: number;
                                    }[];
                                };
                                expenses: {
                                    id: string;
                                    label: string;
                                    color: string;
                                    points: {
                                        label: string;
                                        value: number;
                                    }[];
                                };
                                balance: {
                                    id: string;
                                    label: string;
                                    color: string;
                                    points: {
                                        label: string;
                                        value: number;
                                    }[];
                                };
                                nextMonthPreview?: {
                                    label: string;
                                    income: number;
                                };
                            };
                            expensesByCategory: {
                                total: number;
                                items: {
                                    category: string;
                                    amount: number;
                                    percent: number;
                                    color?: string;
                                }[];
                            };
                            incomeBySource: {
                                total: number;
                                items: {
                                    source: string;
                                    amount: number;
                                    percent: number;
                                    indicatorClassName?: string;
                                }[];
                            };
                            goals: {
                                id: string;
                                name: string;
                                currentAmount: number;
                                targetAmount: number;
                                progressPercent: number;
                                indicatorClassName: string;
                                iconClassName: string;
                            }[];
                            investment: {
                                name: string;
                                indexLabel: string;
                                balance: number;
                                monthChange: {
                                    amount: number;
                                    percent: number;
                                };
                                monthYield: number;
                                yearYield: number;
                            };
                            quickStats: {
                                averageDailySpend: number;
                                largestExpense: {
                                    amount: number;
                                    category: string;
                                };
                                daysRemaining: number;
                                averageDailySurplus: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Relatórios */
        get: {
            parameters: {
                query?: {
                    range?: string;
                    from?: string;
                    to?: string;
                    accounts?: string;
                    categories?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            filters: {
                                range: string;
                                accounts: string[];
                                categories: string[];
                            };
                            incomeVsExpense: {
                                income: {
                                    id: string;
                                    label: string;
                                    points: {
                                        label: string;
                                        value: number;
                                    }[];
                                };
                                expenses: {
                                    id: string;
                                    label: string;
                                    points: {
                                        label: string;
                                        value: number;
                                    }[];
                                };
                            };
                            kpis: {
                                averageIncome: {
                                    amount: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "currency";
                                        direction: "up" | "down" | "neutral";
                                        comparisonLabel?: string;
                                    };
                                };
                                averageExpense: {
                                    amount: number;
                                    delta: {
                                        value: number;
                                        unit: "percent" | "pp" | "currency";
                                        direction: "up" | "down" | "neutral";
                                        comparisonLabel?: string;
                                    };
                                };
                                averageSavingsRate: {
                                    percent: number;
                                    targetPercent: number;
                                };
                            };
                            expensesByCategory: {
                                total: number;
                                items: {
                                    category: string;
                                    amount: number;
                                    percent: number;
                                }[];
                            };
                            monthlySummary: {
                                period: string;
                                income: number;
                                expenses: number;
                                balance: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Projeção patrimonial */
        get: {
            parameters: {
                query?: {
                    timeframe?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            summary: {
                                initialNetWorth: number;
                                plannedMonthlyContribution: number;
                                estimatedAnnualRatePercent: number;
                                projectionIn10Years: number;
                            };
                            timeframe: number;
                            scenarios: {
                                id: string;
                                name: string;
                                type: "base" | "conservative" | "aggressive";
                                points: {
                                    label: string;
                                    value: number;
                                }[];
                            }[];
                            assumptions: {
                                inflationPercent: number;
                                contributionGrowthPercent: number;
                                returnsByClass: {
                                    assetClass: string;
                                    annualRatePercent: number;
                                }[];
                            };
                            compositionAtHorizon: {
                                total: number;
                                items: {
                                    assetClass: string;
                                    amount: number;
                                    percent: number;
                                }[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projections/assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atualizar premissas */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        plannedMonthlyContribution: number;
                        estimatedAnnualRatePercent: number;
                        inflationPercent: number;
                        contributionGrowthPercent: number;
                        returnsByClass: {
                            assetClass: string;
                            annualRatePercent: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            plannedMonthlyContribution: number;
                            estimatedAnnualRatePercent: number;
                            inflationPercent: number;
                            contributionGrowthPercent: number;
                            returnsByClass: {
                                assetClass: string;
                                annualRatePercent: number;
                            }[];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configurações */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            profile: {
                                fullName: string;
                                birthDate?: string;
                                email: string;
                                avatarUrl?: string;
                            };
                            security: {
                                twoFactor: {
                                    enabled: boolean;
                                    method?: string;
                                };
                                passwordLastChanged: string;
                            };
                            preferences: {
                                theme: "dark" | "light" | "system";
                                currency: "BRL" | "USD" | "EUR";
                            };
                            notifications: {
                                weeklyDigest: boolean;
                                dueDateAlerts: boolean;
                                goalsAchieved: boolean;
                            };
                            card: {
                                closingDay?: number;
                                dueDay?: number;
                            };
                            appInfo: {
                                version: string;
                                build: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar perfil */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        fullName?: string;
                        birthDate?: string;
                        avatarUrl?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/settings/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar preferências */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        theme?: "dark" | "light" | "system";
                        currency?: "BRL" | "USD" | "EUR";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/settings/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar notificações */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        weeklyDigest?: boolean;
                        dueDateAlerts?: boolean;
                        goalsAchieved?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/settings/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Configurar cartão (fechamento/vencimento) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        closingDay?: number;
                        dueDay?: number;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/settings/security/two-factor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Configurar 2FA */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        enabled: boolean;
                        method?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/settings/security/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trocar senha */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        currentPassword: string;
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar categorias */
        get: {
            parameters: {
                query?: {
                    type?: "income" | "expense" | "both";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            type: "income" | "expense" | "both";
                            color?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Criar categoria */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        type?: "income" | "expense" | "both";
                        color?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            type: "income" | "expense" | "both";
                            color?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover categoria */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Atualizar categoria */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        type?: "income" | "expense" | "both";
                        color?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            type: "income" | "expense" | "both";
                            color?: string;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            updatedAt: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
